# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicbook',
            name='genres',
            field=models.ManyToManyField(to='books.Genre'),
        ),
    ]
